plugins {
	id 'java'
	id 'war'
	id 'org.springframework.boot' version '3.5.13'
	id 'io.spring.dependency-management' version '1.1.7'
}

group = 'com.google'
version = '0.0.1-SNAPSHOT'

java {
	toolchain {
		languageVersion = JavaLanguageVersion.of(21)
	}
}

repositories {
	mavenCentral()
}

dependencies {
	implementation("com.oracle.database.jdbc:ojdbc11:23.26.1.0.0")
	implementation("org.mybatis.spring.boot:mybatis-spring-boot-starter:3.0.5")
	implementation 'org.springframework.boot:spring-boot-starter-web'
	compileOnly 'org.projectlombok:lombok'
	developmentOnly 'org.springframework.boot:spring-boot-devtools'
	annotationProcessor 'org.projectlombok:lombok'
	providedRuntime 'org.springframework.boot:spring-boot-starter-tomcat'
	testImplementation 'org.springframework.boot:spring-boot-starter-test'
	testCompileOnly 'org.projectlombok:lombok'
	testRuntimeOnly 'org.junit.platform:junit-platform-launcher'
	testAnnotationProcessor 'org.projectlombok:lombok'

	implementation 'org.apache.tomcat.embed:tomcat-embed-jasper'
    implementation 'jakarta.servlet.jsp.jstl:jakarta.servlet.jsp.jstl-api'
    runtimeOnly 'org.glassfish.web:jakarta.servlet.jsp.jstl'
}

eclipse {
    wtp {
        facet {
            facet name: 'jst.web', version: '6.0' // 또는 사용하려는 Dynamic Web Module 버전
            //facet name: 'jst.java', version: '21' // 사용 중인 Java 버전
            // 다른 필요한 Facet도 여기에 추가할 수 있습니다.
        }
    }
}

tasks.named('test') {
	useJUnitPlatform()
}
